# Title shown in Application Information tab.
title: Visual Builder Private Endpoint required resources
# Sub Title shown in Application Information tab.
description: Create the required resources like VCN, Private and Public Subnet, required Gateways and public load balancer to access a private endpoint enabled Visual Builder instance
schemaVersion: 1.1.0
version: "20190304"

# URL of Logo Icon used on Application Information tab. You can copy the contentId from the Marketplace listing logo URL in the Marketplace Partner portal.
# (Optional)
logoUrl: https://cloudmarketplace.oracle.com/marketplace/content?contentId=71617800

locale: "en"
variableGroups:
  - title: General Configuration
    visible: false
    variables:
      - tenancy_ocid
      - region
      - release
      - compartment_ocid

  - title: "Virtual Cloud Network Configuration"
    variables:
      - vcn_cidr
      - vcn_display_name
      - vcn_dns_label

  - title: "Load Balancer Configuration"
    variables:
      - create_public_load_balancer
      - load_balancer_name
      - private_endpoint_ip

######################################################
##############          VARIABLES        #############
######################################################

variables:
  # Hidden variables

######################################################
##############    HIDDEN VARIABLES       #############
######################################################

  tenancy_ocid:
    type: string
    title: Tenancy ID
    description: The Oracle Cloud Identifier (OCID) for your tenancy
    required: true

  region:
    type: oci:identity:region:name
    title: Region
    description: The region in which to create all resources
    required: true

  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    title: Compartment
    description: The compartment in which to create all resources

######################################################
##############     REQUIRED VARIABLES     #############
######################################################

#  compartment_ocid:
#    type: oci:identity:compartment:id
#    required: true
#    title: Compartment
#    description: The compartment in which to create all resources

######################################################
##############     NETWORK VARIABLES     #############
######################################################

  vcn_cidr:
    type: string
    required: false
    default: "10.0.0.0/16"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: CIDR Block
    description: The CIDR of the new Virtual Cloud Network (VCN). Both the public and private subnets will be created by dividing this cidr block equally

  vcn_display_name:
    type: string
    required: false
    default: "Customer-vcn-1"
    title: Name
    description: The name of the new Virtual Cloud Network (VCN)

  vcn_dns_label:
    type: string
    required: true
    title: DNS Label
    default: "customervcn1"
    maxLength: 15
    description: VCN DNS Label. Only letters and numbers, starting with a letter. 15 characters max.


######################################################
##############    LOAD BALANCER VARIABLES     #############
######################################################

  create_public_load_balancer:
    type: boolean
    title: "Create and Configure Public Load Balancer?"
    description: "Create and configure a public load balancer in the public subnet so that the Visual Builder instance is available over internet?"
    visible: true
    default: false

  load_balancer_name:
    type: string
    title: "Load Balancer display name."
    description: "Provide the display name of the public load balancer."
    visible:
      and:
        - create_public_load_balancer
    default: Customer-public-load-balancer-1

  private_endpoint_ip:
    type: string
    title: "Private Endpoint IP for load balancer backend configuration."
    description: "Provide the private endpoint ip that will be used while creating a Private Endpoint enabled Visual Builder instance. This is optional and load balancer backend can be updated with the visual builder's private endpoint ip later."
    visible:
      and:
        - create_public_load_balancer
    default: null
